### ISSUE TITLE
Process error

### ISSUE THREAD

**Issue by disssid** [disssid/Watershed#1]
> java.lang.IllegalStateException: Could not execute method for android:onClick
>    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
>    at android.view.View.performClick(View.java:5637)
>    at android.view.View$PerformClick.run(View.java:22429)
>    at android.os.Handler.handleCallback(Handler.java:751)
>    at android.os.Handler.dispatchMessage(Handler.java:95)
>    at android.os.Looper.loop(Looper.java:154)
>    at android.app.ActivityThread.main(ActivityThread.java:6121)
>    at java.lang.reflect.Method.invoke(Native Method)
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> Caused by: java.lang.reflect.InvocationTargetException
>    at java.lang.reflect.Method.invoke(Native Method)
>    at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
>    at android.view.View.performClick(View.java:5637)
>    at android.view.View$PerformClick.run(View.java:22429)
>    at android.os.Handler.handleCallback(Handler.java:751)
>    at android.os.Handler.dispatchMessage(Handler.java:95)
>    at android.os.Looper.loop(Looper.java:154)
>    at android.app.ActivityThread.main(ActivityThread.java:6121)
>    at java.lang.reflect.Method.invoke(Native Method)
>    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
>    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
> Caused by: CvException [org.opencv.core.CvException: cv::Exception: /Volumes/Linux/builds/master_pack-android/opencv/modules/imgproc/src/color.cpp:8141: error: (-215) (scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F) in function void cv::cvtColor(cv::InputArray, cv::OutputArray, int, int)
>                                                                    ]
>    at org.opencv.imgproc.Imgproc.cvtColor_1(Native Method)
>    at org.opencv.imgproc.Imgproc.cvtColor(Imgproc.java:1724)
>    at com.app.watershed.Watershed.process(Watershed.java:76)
>    at com.app.watershed.NewMainDrawerActivity.watershed(NewMainDrawerActivity.java:423)
>        ... 11 more

**Comment by disssid** [comment]
After recreating the issue, the actual issue was "Permission Denied" to the memory card directory of the file, causing no image to load for processing. 

This caused the exception

`(scn == 3 || scn == 4) && (depth == CV_8U || depth == CV_32F)`

Once the permission was given from 

`Settings -> Apps -> Watershed -> Storage`

the app ran fine.

In order to avoid future instances of such issues and as per the new Android standards a "Permission request" is done as soon as the app is installed and launched. The app continues the process only if the permission is given.
![screenshot_20170901-190014](https://user-images.githubusercontent.com/22083404/29991152-1cb43f34-8f48-11e7-9244-0cd5b4e834f9.png)
![screenshot_20170901-190053](https://user-images.githubusercontent.com/22083404/29991154-1ccc7720-8f48-11e7-9ea9-68b475a738ad.png)
![screenshot_20170901-190028](https://user-images.githubusercontent.com/22083404/29991153-1cc69526-8f48-11e7-8cd9-59dbc16e84ed.png)
![screenshot_20170901-190019](https://user-images.githubusercontent.com/22083404/29991151-1cb1c1c8-8f48-11e7-8d81-a8bdeeed37e6.png)
